apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-developper-api-rest-webapp-k8s
spec:
  selector:
    matchLabels:
      app: challenge-developper-api-rest-webapp-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: challenge-developper-api-rest-webapp-k8s
    spec:
      containers:
        - name: challenge-developper-api-rest-webapp-k8s
          image: challenge-developper-api-rest_webapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080