apiVersion: v1
kind: Service
metadata:
  name: challenge-developper-api-rest-webapp-svc
spec:
  selector:
    app: challenge-developper-api-rest-webapp-k8s
  ports:
    - port: 8080
      nodePort: 30001
  type: LoadBalancer